### ISSUE TITLE
Request: Need to be able to provide a context.Context instance to the Rockset client's HTTP request objects

### ISSUE THREAD

**Issue by smkent** [rockset/rockset-go-client#11]
I'm attempting to use Rockset's custom HTTP client option to add tracing to a service. Our tracing provider library gives us a `http.Client` wrapper that starts a tracing span before each HTTP request.

I'm providing this custom `http.Client` to `RockClient` during initialization:

https://github.com/rockset/rockset-go-client/blob/182b887c3e6a80b4384ca42105028573a6910aef/rockclient.go#L191-L195

This HTTP client wrapper is executing and producing events. However, to connect Rockset HTTP trace events with the rest of an event flow in our application, the tracing library needs to access the existing trace information within a `context.Context` which is where parent span information is stored.

Unfortunately, `RockClient`'s HTTP request creation code does not allow providing a custom `Context` for HTTP requests:

https://github.com/rockset/rockset-go-client/blob/182b887c3e6a80b4384ca42105028573a6910aef/lib/go/client.go#L222-L224

`http.Request` supports this upstream with either [NewRequestWithContext](https://golang.org/pkg/net/http/#NewRequestWithContext) or the [Request.WithContext](https://golang.org/pkg/net/http/#Request.WithContext) option.

**Can you add support for providing a request context to the Rockset client?** Thanks!

**Comment by pmenglund** [comment]
I have a new version of the client in the works that uses [go-swagger](https://github.com/go-swagger/go-swagger) to generate the client, which passes `context.Context`. I will ping you when I've pushed the branch and you can test the alpha version of the client.

**Comment by smkent** [comment]
@pmenglund That would be delightful! Thank you!

**Comment by pmenglund** [comment]
@smkent small snag, the go-swagger client is very strict, so it requires the [spec](https://github.com/rockset/openapi/blob/master/spec2.yaml) to explicitly list all http response codes, or you'll get this:

```
2021/01/28 08:45:59 response status code does not match any response statuses defined for this endpoint in the swagger spec (status 404): {}
```

So I'm working with the other engineering teams to add that.

**Comment by pmenglund** [comment]
@smkent finally resolved all issues to be able to build an alpha version of the new client, see the branch:
https://github.com/rockset/rockset-go-client/tree/go-swagger

There are still a lot of missing features, especially convenience functions for the most common operations, e.g. executing queries, collection operations, workspace operations.

**Comment by pmenglund** [comment]
@smkent version 0.12 is out which supports passing a context

**Comment by pmenglund** [comment]
fixed in https://github.com/rockset/rockset-go-client/commit/874a52ad7f3e36de64b5940efddc6b8a7c0ae329
